const db = require('./index.js')
const Image =  require('./Schema.js')
const faker = require('faker')

// sampleImage = {
//   itemId: null,
//   color: "",
//   url: ""
// }

/*
i want 100 itemIds
  -the itemIds can be generated by incrementing
i want 2 colors for every itemId
  -the colors can be randomly generated with a helper function
i want 3 picture urls for every color
  -the urls come from the S3 bucket
  `<url>${i}`
*/
// const randomColor = faker.internet.color()
// const generateRandomData = () => {
  
//   return  sampleImage = {
//     itemId: null,
//     color: '',
//     url: ''
//   }
// }
const dataGen = () => {
  let dataArr = [];
  let colorArr = ['coral', 'black']
for (let k = 0; k < 600; k++) {
  if (Math.floor(k/3) % 2 === 0) {
    dataArr.push({
      itemId: Math.floor(k/6),
      color: colorArr[0],
      url: `https://fec-clothes-images.s3-us-west-2.amazonaws.com/image${k}.jpeg`
    })
  }
  if ((Math.floor(k/3) % 2 !== 0)) {
    dataArr.push({
      itemId: Math.floor(k/6),
      color: colorArr[1],
      url: `https://fec-clothes-images.s3-us-west-2.amazonaws.com/image${k}.jpeg`
    })
  }
}
return dataArr
}
randomDataArray = [
  {itemId: 0, color: 'coral', url: 'https://fec-clothes-images.s3-us-west-2.amazonaws.com/image0.jpeg'}, 
{itemId: 0, color: 'coral', url: 'https://fec-clothes-images.s3-us-west-2.amazonaws.com/image1.jpeg'},
   {itemId: 0, color: 'coral', url: 'https://fec-clothes-images.s3-us-west-2.amazonaws.com/image2.jpeg'}, 
   {itemId: 0, color: 'black', url: 'https://fec-clothes-images.s3-us-west-2.amazonaws.com/image3.jpeg'}, 
   {itemId: 0, color: 'black', url: 'https://fec-clothes-images.s3-us-west-2.amazonaws.com/image4.jpeg'}, 
   {itemId: 0, color: 'black', url: 'https://fec-clothes-images.s3-us-west-2.amazonaws.com/image5.jpeg'}];

const insertSampleImage = () => {
  Image.create(dataGen())
  // .then(()=> db.disconnect())
}

insertSampleImage();