const db = require('./index.js')
const Image =  require('./Schema.js')
const faker = require('faker')

// sampleImage = {
//   itemId: null,
//   color: "",
//   url: ""
// }

/*
i want 100 itemIds
  -the itemIds can be generated by incrementing
i want 2 colors for every itemId
  -the colors can be randomly generated with a helper function
i want 600 urls
  -the urls come from the S3 bucket
  `<url>${i}`
*/
const randomColor = faker.internet.color()

const generateRandomData = () => {
  return  sampleImage = {
    itemId: null,
    color: '',
    url: ''
  }
}
